spring:
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
  datasource:
    url: mysql://localhost:3306/INT_YSUMMA
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 9T%2#7eErrc1
    hikari:
      connection-test-query: SELECT 1
      validationTimeout: 120000
  batch:
    initialize-schema: always

app:
  chunk:
    size: 4
  file: C:\interbank\bie\resources\pruebas\employee_v4.txt
